apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-jquery-dep
  namespace: jquery
  labels:
    app: jquery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jquery
  template:
    metadata:
      labels:
        app: jquery
    spec:
      containers:
      - name: jquery
        image: 026657017754.dkr.ecr.ap-southeast-1.amazonaws.com/jqurey-eks:number
        ports:
        - containerPort: 80
