apiVersion: v1
kind: Service
metadata:
  name: k8-jquery-svc
  namespace: jquery
spec:
  selector:
    app: jquery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer